export const eventList = {
    Sports: [
        {
            type: "Basketball",
            name: "Basketball Game",
            venue: "Stadium Arena",
            date: "2023-06-15",
            time: "19:00",
            ticketsAvailable: 300,
            price: 50,
            imgUrl: "https://st.depositphotos.com/1269924/4622/i/600/depositphotos_46221797-stock-photo-basketball-going-through-the-basket.jpg",
        },
        {
            type: "Football",
            name: "Football Match",
            venue: "City Stadium",
            date: "2023-07-02",
            time: "20:30",
            ticketsAvailable: 300,
            price: 40,
            imgUrl: "https://thumbs.dreamstime.com/b/football-soccer-ball-kickoff-game-sunset-38302251.jpg",
        },
        {
            type: "Soccer",
            name: "Soccer Championship",
            venue: "Sports Complex",
            date: "2023-06-20",
            time: "18:30",
            ticketsAvailable: 400,
            price: 35,
            imgUrl: "https://thumbs.dreamstime.com/b/football-soccer-ball-kickoff-game-sunset-38302251.jpg",
        },
        {
            type: "Tennis",
            name: "Grand Slam Tournament",
            venue: "Tennis Center",
            date: "2023-07-10",
            time: "14:00",
            ticketsAvailable: 200,
            price: 25,
            imgUrl: "https://media.istockphoto.com/id/1171084311/photo/tennis-rackets-and-balls-leaned-against-the-net.jpg?s=612x612&w=0&k=20&c=SnDgfU30k0PMfVjSHTv4umDQWwKtUHJ8AEgofJXg6w4=",
        },
        {
            type: "Cricket",
            name: "Cricket Match",
            venue: "Cricket Ground",
            date: "2023-07-20",
            time: "10:00",
            ticketsAvailable: 400,
            price: 30,
            imgUrl: "https://media.istockphoto.com/id/177427917/photo/close-up-of-red-cricket-ball-and-bat-sitting-on-grass.jpg?s=612x612&w=0&k=20&c=DcorerbBUeDNTfld3OclgHxCty4jih2yDCzipffX6zw=",
        },
    ],
    Theater: [
        {
            type: "Shakespearean",
            name: "Shakespearean Play",
            venue: "City Theater",
            date: "2023-06-30",
            time: "19:30",
            ticketsAvailable: 250,
            price: 30,
            imgUrl: "https://img.freepik.com/free-vector/dark-theater-stage-with-red-curtains-spotlight_107791-2000.jpg?w=2000",
        },
        {
            type: "Musical",
            name: "Musical Extravaganza",
            venue: "Grand Opera House",
            date: "2023-07-15",
            time: "19:00",
            ticketsAvailable: 400,
            price: 45,
            imgUrl: "https://images.unsplash.com/photo-1503095396549-807759245b35?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dGhlYXRyZXxlbnwwfHwwfHx8MA%3D%3D&w=1000&q=80",
        },
        {
            type: "Drama",
            name: "Classic Drama Performance",
            venue: "Community Theater",
            date: "2023-07-08",
            time: "20:00",
            ticketsAvailable: 150,
            price: 25,
            imgUrl: "https://thumbs.dreamstime.com/b/movie-theatre-22314923.jpg",
        },
    ],
    Movies: [
        {
            type: "Action",
            name: "Blockbuster Action Movie",
            venue: "Cinema Theater",
            date: "2023-06-25",
            time: "21:00",
            ticketsAvailable: 200,
            price: 20,
            imgUrl: "https://media.istockphoto.com/id/911590226/vector/movie-time-vector-illustration-cinema-poster-concept-on-red-round-background-composition-with.jpg?s=612x612&w=0&k=20&c=QMpr4AHrBgHuOCnv2N6mPUQEOr5Mo8lE7TyWaZ4r9oo=",
        },
        {
            type: "Comedy",
            name: "Hilarious Comedy Flick",
            venue: "Local Movie House",
            date: "2023-07-05",
            time: "19:30",
            ticketsAvailable: 100,
            price: 15,
            imgUrl: "https://media.istockphoto.com/id/911590226/vector/movie-time-vector-illustration-cinema-poster-concept-on-red-round-background-composition-with.jpg?s=612x612&w=0&k=20&c=QMpr4AHrBgHuOCnv2N6mPUQEOr5Mo8lE7TyWaZ4r9oo=",
        },
        {
            type: "Drama",
            name: "Award-Winning Drama Film",
            venue: "Indie Cinema",
            date: "2023-07-20",
            time: "18:30",
            ticketsAvailable: 120,
            price: 18,
            imgUrl: "https://media.istockphoto.com/id/911590226/vector/movie-time-vector-illustration-cinema-poster-concept-on-red-round-background-composition-with.jpg?s=612x612&w=0&k=20&c=QMpr4AHrBgHuOCnv2N6mPUQEOr5Mo8lE7TyWaZ4r9oo=",
        },
    ],
    Concerts: [
        {
            type: "Rock",
            name: "Rock Band Live",
            artist: "The Rock Band",
            venue: "Music Hall",
            date: "2023-06-25",
            time: "20:00",
            ticketsAvailable: 300,
            price: 55,
            imgUrl: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGNvbmNlcnR8ZW58MHx8MHx8fDA%3D&w=1000&q=80",
        },
        {
            type: "Pop",
            name: "Pop Star World Tour",
            artist: "Pop Star",
            venue: "Outdoor Amphitheater",
            date: "2023-07-10",
            time: "19:30",
            ticketsAvailable: 500,
            price: 60,
            imgUrl: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8Y29uY2VydHxlbnwwfHwwfHx8MA%3D%3D&w=1000&q=80",
        },
        {
            type: "Jazz",
            name: "Jazz Festival",
            artist: "Jazz Band",
            venue: "City Park",
            date: "2023-07-18",
            time: "18:00",
            ticketsAvailable: 200,
            price: 30,
            imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSA19DjIo6L8THAYegiPK9LO1w13uwhMZEnkOSgcI0&s",
        },
    ],
};
